# Generated by Django 3.2.5 on 2021-07-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_reporteauditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteImpresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workgroup_name', models.CharField(max_length=100)),
                ('impresora', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
