# Generated by Django 3.2.5 on 2021-07-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_reporteimpresion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteCancelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
                ('impresora', models.CharField(max_length=100)),
            ],
        ),
    ]
