# Generated by Django 3.2.5 on 2021-07-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100)),
                ('workgroup_id', models.CharField(max_length=100)),
                ('workgroup_name', models.CharField(max_length=100)),
                ('admin_acount', models.CharField(max_length=100)),
            ],
        ),
    ]
