# Generated by Django 3.2.5 on 2021-08-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_recursos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_maker', models.IntegerField()),
                ('id_ayudante', models.IntegerField()),
                ('tipo_maquina', models.CharField(max_length=100)),
                ('habilitado_o_no', models.CharField(max_length=20)),
                ('recursos', models.CharField(max_length=500)),
            ],
        ),
    ]
