# Generated by Django 3.2.5 on 2021-08-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_habilitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinas',
            name='reservado',
            field=models.CharField(default='no reservado', max_length=100),
            preserve_default=False,
        ),
    ]
